/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_triangulation_TriangulationData */

#ifndef _Included_bits_triangulation_TriangulationData
#define _Included_bits_triangulation_TriangulationData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    alloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bits_triangulation_TriangulationData_alloc
  (JNIEnv *, jclass);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    free
 * Signature: (JZZZ)V
 */
JNIEXPORT void JNICALL Java_bits_triangulation_TriangulationData_free
  (JNIEnv *, jclass, jlong, jboolean, jboolean, jboolean);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    setPoints
 * Signature: (JLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_bits_triangulation_TriangulationData_setPoints
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    setSegments
 * Signature: (JLjava/nio/IntBuffer;II)V
 */
JNIEXPORT void JNICALL Java_bits_triangulation_TriangulationData_setSegments
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    setHoles
 * Signature: (JLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_bits_triangulation_TriangulationData_setHoles
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    getPointCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_triangulation_TriangulationData_getPointCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    getPoints
 * Signature: (JLjava/nio/DoubleBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_bits_triangulation_TriangulationData_getPoints
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    getTriangleCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_triangulation_TriangulationData_getTriangleCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    getTriangles
 * Signature: (JLjava/nio/IntBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_bits_triangulation_TriangulationData_getTriangles
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    getEdgeCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_triangulation_TriangulationData_getEdgeCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    getEdges
 * Signature: (JLjava/nio/IntBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_bits_triangulation_TriangulationData_getEdges
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     bits_triangulation_TriangulationData
 * Method:    triangulate
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_bits_triangulation_TriangulationData_triangulate
  (JNIEnv *, jclass, jlong, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
